import os
from .models import AuditResult

class MarkdownReporter:
    def __init__(self):
        pass

    def generate_markdown(self, result: AuditResult, output_path: str):
        sub = result.submission
        score = result.overall_score
        
        md = f"# Visibility Audit: {sub.business_name}\n"
        md += f"**URL**: {sub.website_url}\n"
        md += f"**Date**: {sub.timestamp.strftime('%Y-%m-%d')}\n\n"
        
        md += f"# Overall Score: {score.total_points} / {score.max_total_points}\n"
        md += f"**Grade**: {score.grade}\n\n"
        
        md += "## Layer Breakdown\n\n"
        
        for layer in score.layer_scores:
            md += f"### Layer {layer.layer_id}: {layer.name}\n"
            md += f"**Score**: {layer.points_earned} / {layer.max_points} ({layer.percentage:.1f}%)\n\n"
            
            md += "| Status | Task | Reasoning |\n"
            md += "| :--- | :--- | :--- |\n"
            
            for task in layer.tasks:
                icon = "✅" if task.status.value == "PASS" else "⚠️" if task.status.value == "WARN" else "❌"
                md += f"| {icon} {task.status.value} | {task.name} | {task.reasoning} |\n"
            
            md += "\n"
            
            md += "\n"

        # AI Narrative Section
        ai = score.ai_narrative
        md += "## AI Visibility Summary\n"
        if ai.get('benchmark_text'):
             md += f"_{ai['benchmark_text']}_\n\n"
             
        md += f"**Readiness**: \"{ai.get('readiness_explanation', 'N/A')}\"\n\n"
        
        md += f"**Bottleneck**: \"{ai.get('bottleneck_impact', 'N/A')}\"\n\n"
        
        md += f"### Fastest Score Gains\n"
        for step in ai.get('fastest_gains', []):
            md += f"* {step}\n"
            
        md += f"\n**Closing**: \"{ai.get('closing_line', 'N/A')}\"\n"
            
        md += "\n---\nGenerated by PPM AI Visibility Audit Automation\n"
        
        # Ensure output directory exists
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        
        with open(output_path, "w") as f:
            f.write(md)
            
        print(f"Markdown report generated at: {output_path}")
